name: Update README

on:
  release:
    types: [published]

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch latest release
      id: fetch_release
      run: |
        release_url=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | grep '"html_url":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "release_url=$release_url" >> $GITHUB_OUTPUT

    - name: Update README
      run: |
        readme_path="README.md"
        table_start="<!-- RELEASE_TABLE_START -->"
        table_end="<!-- RELEASE_TABLE_END -->"

        table="| OS | Download |\n|---|---|\n"
        table+="| Linux (64-bit) | [Download](${{ steps.fetch_release.outputs.release_url }}/dsRNAmax-linux-amd64) |\n"
        table+="| Linux (ARM64) | [Download](${{ steps.fetch_release.outputs.release_url }}/dsRNAmax-linux-arm64) |\n"
        table+="| Windows (64-bit) | [Download](${{ steps.fetch_release.outputs.release_url }}/dsRNAmax-windows-amd64.exe) |\n"
        table+="| macOS (Intel) | [Download](${{ steps.fetch_release.outputs.release_url }}/dsRNAmax-darwin-amd64) |\n"
        table+="| macOS (Apple Silicon) | [Download](${{ steps.fetch_release.outputs.release_url }}/dsRNAmax-darwin-arm64) |\n"

        sed -i -e "/$table_start/,/$table_end/{ /$table_start/{p; r /dev/stdin
        }; /$table_end/p; d }" $readme_path <<< "$table"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with latest release links" || echo "No changes to commit"
        git push